version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps-{{ checksum "requirements.txt" }}
      - run:
          name: Setup environments
          command: ./setup_environments.sh
      - run:
          name: Run tests
          command: ./run_tests.sh

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "example/venv"
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload:
        file: './coverage/clover.xml'
        token: a7a5df63-codcov-token-4278vh38
