from enum import Enum


class JSONAPIVersion(Enum):
    JSONAPI_RC2 = "1.0RC2"
    JSONAPI_RC3 = "1.0RC3"
    JSONAPI_1_0 = "1.0"


JSONAPI_VALID_VERSIONS = [JSONAPIVersion.JSONAPI_RC2, JSONAPIVersion.JSONAPI_RC3, JSONAPIVersion.JSONAPI_1_0]
JSONAPI_DEFAULT_VERSION = JSONAPIVersion.JSONAPI_1_0


def get_default_version():
    return JSONAPI_DEFAULT_VERSION
